### ISSUE TITLE
BookStack 1-click support

### ISSUE THREAD

**Issue by jonaharagon** [apisnetworks/apnscp#12]
This would be helpful for me. Installation is pretty similar to Laravel which IIRC is already supported.

- [Installation instructions](https://www.bookstackapp.com/docs/admin/installation/)
- [CLI administration](https://www.bookstackapp.com/docs/admin/commands/) (`php artisan bookstack:`)

**Comment by msaladna** [comment]
Reduce this down to mother tongue/framework. Having an explicit option to install BookStack would lend itself to pollution just as much as Laravel does and Spark would both of which contribute to this problem. Instead have a mother tongue option to install Laravel/BookStack/Spark/Drupal/etc. They all use the same mechanism (composer) and all of it can tie into [pman_run](https://api.apnscp.com/class-Pman_Module.html#_run). Will work this into 3.1. It's a good way to fan out app delivery for apps based upon Composer 👍

**Comment by msaladna** [comment]
v3.1.45 is next on the release list and will open up the Web Apps API for third-party contributions. Should be here in a week or two.

**Comment by msaladna** [comment]
[ApisCP 3.2](https://hq.apiscp.com/apiscp-3-2-released/) has been released which opens up the door for possibility with third-party web apps. A demo app is available via [apisnetworks/apiscp-webapp-demo](https://github.com/apisnetworks/apiscp-webapp-demo) that provides some guidance on rolling your own app. I will not be able to implement this app directly, but leave the task up to you or anyone else that chooses to undertake it.
