### ISSUE TITLE
Feature Request: Offsite backup

### ISSUE THREAD

**Issue by mminglis** [apisnetworks/apnscp#16]
Offsite scheduled file and db backup to different locations (eg S3 / Dropbox / local NAS) would be amazing.

**Comment by possibleworlds** [comment]
Offsite scheduled file and db backup to different locations (eg S3 / Dropbox / local NAS) would be amazing.

**Comment by msaladna** [comment]
A drop-in package for Bacula is now available, [apnscp-bacula](https://github.com/apisnetworks/apnscp-bacula). [Restic](https://restic.net/) was mentioned as well which looks to be a compact solution for individual backups. 

Will have more on this in the coming weeks since focus has abruptly shifted to building an import facility for cPanel backups.

**Comment by MACscr** [comment]
Bacula is a bit of a pain to setup, especially when doing WAN backups that require TLS encryption. Ive been looking at restic and borg as option, but haven't settled on which one is the better way to go. Reliability, efficiency, and easy of management are what I'm looking at.

**Comment by tturnerdev** [comment]
Highly recommend diff-able (dedup) backup solution such as [borg](https://github.com/borgbackup/borg), [duplicacy](https://duplicacy.com/), etc.

Edit: I was shopping for new backup system and looked into Restic. It's solid, and I would choose it if I wanted to go the rsync route, but I don't think that's the best direction to go with all the features of more modern systems. Still rsync is good at what it does.

**Comment by MACscr** [comment]
> Highly recommend diff-able (dedup) backup solution such as [borg](https://github.com/borgbackup/borg), [duplicacy](https://duplicacy.com/), etc.

Yep, i switched to borg, using it with borgmatic and borgbase.

**Comment by domaingood** [comment]
What about SFTP/Google Drive backup Solutions? Those are secure and cheap.

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#3](https://feedback.apiscp.com/posts/3/duplicity-drop-in-support) and [feedback.apiscp.com#20](https://feedback.apiscp.com/posts/20/built-in-backups-restores)
