### ISSUE TITLE
Mailing Lists available when disabled for account

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#17]
mlist is disabled for the account for in the latest 3.1 as of today, but the mailing list button is still showing for the user and when clicked on, gives them mailing list options.

**Comment by msaladna** [comment]
Thanks for the bug report. This has been fixed in master and will be slated for inclusion in v3.0.43. In the meanwhile you can put your panel in edge mode to test the new code.

```bash
cpcmd config:set apnscp.update-policy edge
upcp
```
