### ISSUE TITLE
Wordpress Updates Fail completely if single plugin cant be updated

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#23]
sometime commercial plugins fail because a user has a plugin that came free with their theme, etc, but they dont get free automated updates. Seems the entire worpdress update fails when this happens:

![image](https://user-images.githubusercontent.com/1404944/68758919-537b0c00-05d4-11ea-88e8-111e2889a11b.png)

**Comment by msaladna** [comment]
As the account admin (su domain.com) and within the doc root for WP:

`wp-cli --skip-plugins plugin list` and `wp-cli plugin list` - is the custom plugin missing in the former? Does it throw any errors? What's the status/update field for that plugin?

**Comment by msaladna** [comment]
Skiplist implementation in the frontend resolves this in v3.1.40. Corresponding wordpress:skip_asset($hostname, $path, $name, $type) or Manage Packages in Web > Web Apps provides a frontend to manage this.
