### ISSUE TITLE
cPanel Importer autoresponders

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#24]
```postfix/error[25486]: BA0A17DE52: to=<|/usr/local/cpanel/bin/autorespond,matt@iabcent.com, /home/iabcente/.autorespond>, orig_to=<matt@iabcent.com>, relay=none, delay=1.5, delays=1.5/0.01/0/0.01, dsn=5.1.3, status=bounced (bad address syntax)```

Seems to be importing the cpanel autoresponders incorrectly and causing problems. Probably best to not import them if they dont import cleanly? Not a big deal imho if importing them isnt supported. Would rather them not be imported if they are going to cause problems like above

**Comment by msaladna** [comment]
Issue seems to still be pending. Provide a scrubbed backup that embodies this setup (autoresponder, vacation, local delivery) so I can look further into this.

**Comment by msaladna** [comment]
Autoresponders are converted to an aliased delivery. 

There's an incompatibility baked into mail handling in which all autoresponders go to the primary user. Autoresponders should deliver to the respective user account instead for processing. Discussed in the [caveats](https://gitlab.com/apisnetworks/apnscp/-/blob/master/docs/admin/Migrations.md#caveats) section of migrations.
