### ISSUE TITLE
php-pools gui 500 error

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#26]
I get the following error when clicking on php-pools in the web gui. Latest edge version as of this post.

> [Mon Dec 09 07:42:26.596830 2019] [php7:error] [pid 9685:tid 140391164651264] [client X.X.X.X:56709] PHP Fatal error:  Page_Container and FilesystemPathTrait define the same property ($site) in the composition of apps\\php_pools\\Page. However, the definition differs and is considered incompatible. Class was composed in /usr/local/apnscp/apps/php-pools/php-pools.php on line 33, referer: https://myscrubbedhostname.com:2083/apps/dashboard

**Comment by msaladna** [comment]
Resolved in [latest commit](https://gitlab.com/apisnetworks/apnscp/commit/99d51f43191c92d69a5785e10940994672001730)
