### ISSUE TITLE
Mastodon 1-click support

### ISSUE THREAD

**Issue by jonaharagon** [apisnetworks/apnscp#33]
Mastodon is a Node.js & Ruby on Rails social media platform with a large community and user base being mostly hosted in VPS environments. If it's possible to add I think it would be a really great addition, especially as a more unique offering.

[Installation](https://docs.joinmastodon.org/admin/install/)

**Comment by msaladna** [comment]
This is better served with opening up a 1-click framework so my role doesn't morph into building the next Softaculous and that others can maintain these individual packages. I do not have an estimate when this framework will be opened up, but will update accordingly.

**Comment by msaladna** [comment]
v3.1.45 is next on the release list and will open up the Web Apps API for third-party contributions. Should be here in a week or two.

**Comment by msaladna** [comment]
[ApisCP 3.2](https://hq.apiscp.com/apiscp-3-2-released/) has been released which opens up the door for possibility with third-party web apps. A demo app is available via [apisnetworks/apiscp-webapp-demo](https://github.com/apisnetworks/apiscp-webapp-demo) that provides some guidance on rolling your own app. 

This app is a little different in its systemd requirements (sidekiq removed daemonization in v6), so this is a bit of a different case. 3.2 is enhancing one-click support for Ruby/Node/Python apps.

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#36](https://feedback.apiscp.com/posts/36/mastodon-1-click-support)
