### ISSUE TITLE
Password Protect Directories

### ISSUE THREAD

**Issue by shahaly** [apisnetworks/apnscp#36]
**Request** 
Ability to create password protected directory.

**Role**
Webmaster View / End User Panel 

**User Story**
As a user logged in to manage my domain, I would love to be able to create password protected directories. The contents within the directory should only be visible and accessible by a remote entity if they pass the password challenge successfully. 

**Use Case**
Say I have a file that I want to share with my team but not the entire world. I own a domain called domain.tld. It would be nice if I were under File Manager, I could create a directory in the main html folder called personal and set a password for it. Then I could upload files to it and ask my team to visit https://domain.tld/personal to retrieve the files. Upon visiting the website, the users must successfully enter the password.

**Security**
Existing Rampart protections should continue to apply.

**Secondary Feature**
Would love it if were a scope that could be enabled or disabled by the server admin for the accounts on their Apiscp instance.

**Workaround Today**
Using OneDrive, Sharefile, etc. to do this. I could theoretically install NextCloud and do this too.

**Comment by msaladna** [comment]
Will get this penciled into an upcoming 3.2 release. You can use it from terminal using htpasswd as well. Part of the issue is that httpd-tools is missing from the filesystem template. This will fix it:

```bash
/usr/local/apnscp/bin/scripts/install_fs_pkg.sh httpd-tools siteinfo
systemctl reload fsmount
```


```bash
su site1
cd /var/www
htpasswd -c .htpasswd test
``` 

Then in /var/www/html/.htaccess,

```
AuthType Basic
AuthName "Protected area"
AuthUserFile /home/virtual/site1/fst/var/www/.htpasswd
Require valid-user
```

Apache has different visibility than PHP-FPM or shell, so use the [full filesystem](https://docs.apiscp.com/admin/Filesystem/) path.

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#37](https://feedback.apiscp.com/posts/37/password-protect-directories)
