### ISSUE TITLE
May I know any dockerization or high availability?

### ISSUE THREAD

**Issue by ckc** [apisnetworks/apnscp#37]
Like as subject mentioned, we are concerning about the redundancy / fail-over

**Comment by msaladna** [comment]
ApisCP supports [Docker](https://docs.apiscp.com/admin/Docker/) but as it’s an operating system enhancement for CentOS/RHEL, cannot itself run containerized. 

Does this address your question?

**Comment by ckc** [comment]
> ApisCP supports [Docker](https://docs.apiscp.com/admin/Docker/) but as it’s an operating system enhancement for CentOS/RHEL, cannot itself run containerized.
> 
> Does this address your question?

Thank your for the prompt reply 
The containerized would be our consideration but the most important is high availability (like  Multiserver,Cluster and dedicated services (Web, Email, DNS & Maria DB Servers) environment)

Addition is multiple PHP versions, I think just only two are enough (as you may know only huge different and majority 5.x & 7.x)

**Comment by msaladna** [comment]
Clustering is not turnkey in this platform. You'd be responsible for deploying your own infrastructure changes on top of ApisCP to achieve such a layout. Clustered mail and database will break native storage quota limits as well, which is contrary to ApisCP's design goals.
