### ISSUE TITLE
Feature Request: Web App Updates Logs

### ISSUE THREAD

**Issue by MACscr** [apisnetworks/apnscp#38]
Would love to have the Web App UI show have some sort of dated log list that shows X number of recent updates that apiscp has performed on the app. Like x,y,z plugins updated on 10/29/2020 at 7:20pm, etc. Thoughts? Would be cool if that could be tied into the snapshots if enabled for being able to restore before that particular update. Just something to make things more user friendly and intuitive.

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#38](https://feedback.apiscp.com/posts/38/web-app-update-logs)
