### ISSUE TITLE
Digital Ocean Block Storage

### ISSUE THREAD

**Issue by msaladna** [apisnetworks/apnscp#4]
As [requested](https://www.reddit.com/r/webhosting/comments/6rqivg/serverpilot_vs_runcloud_vs_easyengine_or_any/dl85stc/) on Reddit by /u/Dibbyo123.

Add ability to attach/detach block storage on-the-fly in apnscp. Could in theory also provide the storage basis for a new account, although database access will suffer.

**Comment by harryqt** [comment]
Also, mounting to the apps/websites.

**Comment by themainframech** [comment]
Progress?

**Comment by msaladna** [comment]
Have the [option](https://bitbucket.org/apisnetworks/apnscp/src/master/lib/Opcenter/Service/Validators/Files/Mounts.php) squared away as part of the files configuration group. Will integrate it before alpha.

**Comment by msaladna** [comment]
Scheduled for [3.1](https://www.reddit.com/r/apnscp/comments/azjupa/v3023_released_transitioning_to_v31_development/)

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#29](https://feedback.apiscp.com/posts/29/digitalocean-block-storage)
