### ISSUE TITLE
Long Bootstapping Time

### ISSUE THREAD

**Issue by skills-up** [apisnetworks/apnscp#40]
Hi,

This is the first time I'm trying APIS CP on a freshly provisioned 32GB RAM Performance+ VPS from SSD Nodes.

It has been over 3 hours and the bootstrap installation is still going on. Last task was `TASK [system/yum : Configure yum]`

There was no error except `Failure downloading http://pkg.cloudflare.com/cloudflare-release-latest.el7.rpm` but the installation continued despite the error.

Should I be worried?

**Comment by msaladna** [comment]
What's your source on this? Watching terminal or tailing `/root/apnscp-bootstrapper.log`? I run E2Es frequently to evaluate builds and they've [completed without incident](https://api.ara.apiscp.com/)  over the last 72 hours. 

Depending on OS, CentOS 7 or 8/Stream there will be 1 or 2 reboots as a patch is required for Ansible 2.9.16 in C8. If you're checking via `tail -f /root/apnscp-bootstrapper.log`, let me know on the server configuration from SSDNodes + OS for further evaluation.

**Comment by msaladna** [comment]
No response. Suspending issue.
