### ISSUE TITLE
cpcmd: No Error Handling

### ISSUE THREAD

**Issue by topperharly** [apisnetworks/apnscp#41]
cpcmd add any value to apnscp-vars-runtime.yml, without information that the value is unknown or not used by upcp -sb

```
cpcmd scope:set cp.bootstrapper thisisatest ilikeapiscp
INFO    : Setting variable `thisisatest'. Previous not present in apnscp-vars-runtime.yml.
----------------------------------------
MESSAGE SUMMARY
Reporter level: OK
INFO: Setting variable `thisisatest'. Previous not present in apnscp-vars-runtime.yml.
----------------------------------------
1

cat ~/apnscp-vars-runtime.yml |grep thisis
thisisatest: ilikeapiscp

upcp -bs system/sshd

PLAY [localhost] ********************************************************************************************************************************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0

```

This results in confused users/admins when you only has a typo in a value, especially when in both cases cpcmd Reporter succeeded with  1

for example: 

` cpcmd scope:set cp.bootstrapper permitRootLogin yes`  <- the wrong value but not recognized
not equal to
 `cpcmd scope:set cp.bootstrapper PermitRootLogin yes` <- the right value

**Comment by msaladna** [comment]
This is expected operation for the cp.bootstrapper Scope, which writes arbitrary well-formed Yaml to /root/apnscp-vars-runtime.yml. These vars take precedence in Bootstrapper whenever `upcp -sb` is run. 

If you'd like to see what possible settings may be set for a role, consider its complement scope:get

```bash
# Show all global overrides
cpcmd scope:get cp.bootstrapper
# Show defaults for system/sshd
cpcmd scope:get cp.bootstrapper system/sshd
```

If you wanted to override sshd_template for example,

```bash
cpcmd scope:set cp.bootstrapper sshd_template "
MaxAuthTries {{ sshd_max_auth_tries }}
GSSAPIAuthentication no
X11Forwarding no
ClientAliveInterval 180
PermitRootLogin without-password
UseDNS {{ sshd_use_dns | ternary("yes", "no") }}
"
```

See also **Scopes** app in the panel or [Bootstrapper](https://docs.apiscp.com/admin/Bootstrapper/#configuration) >> Configuration on docs.apiscp.com.
