### ISSUE TITLE
Installation Issues on CentOS 8 with or Without Config Utility

### ISSUE THREAD

**Issue by natpix** [apisnetworks/apnscp#42]
### First Issue: 

`RUNNING HANDLER [filesystem/make-mounts : Restart polkitd] *********************
fatal: [localhost]: FAILED! => changed=false
  msg: 'Could not find the requested service polkit: host'

RUNNING HANDLER [filesystem/swap : Reload sysctl] ******************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=58   changed=26   unreachable=0    failed=1    skipped=42   rescued=0    ignored=0

ERR: Stage 2 bootstrap failed
Run 'cd /usr/local/apnscp/resources/playbooks && env ANSIBLE_LOG_PATH=/root/apnscp-bootstrapper.log BOOTSTRAP_SH=/root/resume_apnscp_setup.sh  ansible-playbook -l localhost -c local bootstrap.yml' to resume
Installation failed`

After running **_cd /usr/local/apnscp/resources/playbooks && env ANSIBLE_LOG_PATH=/root/apnscp-bootstrapper.log BOOTSTRAP_SH=/root/resume_apnscp_setup.sh  ansible-playbook -l localhost -c local bootstrap.yml_**

TASK [apnscp/assert-admin-works : Start apnscp] ************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Unable to start service apnscp: Job for apnscp.service failed because a timeout was exceeded.
    See "systemctl status apnscp.service" and "journalctl -xe" for details.

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=737  changed=254  unreachable=0    failed=1    skipped=219  rescued=1    ignored=11

**Comment by msaladna** [comment]
[polkit](https://wiki.archlinux.org/index.php/Polkit) is a common system package part of the security infrastructure in Red Hat/CentOS (among others). Based on a most recent [run](https://api.ara.apiscp.com/files/101903.html#line-21), this service exists with vendors tested.

Who is your cloud vendor and if you provisioned self, which installation profile did you select when installing CentOS?

**Comment by natpix** [comment]
SSDNODE is the cloud provider

i used ApisCP Doc 

curl https://raw.githubusercontent.com/apisnetworks/apnscp-bootstrapper/master/bootstrap.sh | bash

**Comment by msaladna** [comment]
Reboot the server then try installing again. I’ve seen this in a few situations with CentOS that systemd rejects all directives.

After restarting, `rm -rf /usr/local/apnscp` then run the installer again.

**Comment by natpix** [comment]
okay let me try this now

**Comment by natpix** [comment]
TASK [apnscp/initialize-db : Populate APNSCP_APPLIANCE_DB] *********************
ok: [localhost]

RUNNING HANDLER [common : Restart apnscp] **************************************
fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Unable to restart service apnscp: Job for apnscp.service failed because a timeout was exceeded.
    See "systemctl status apnscp.service" and "journalctl -xe" for details.

RUNNING HANDLER [common : Restart apnscp] **************************************

RUNNING HANDLER [common : Restart virtualhosting] ******************************

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=597  changed=67   unreachable=0    failed=1    skipped=252  rescued=0    ignored=11

ERR: Stage 2 bootstrap failed
Run 'cd /usr/local/apnscp/resources/playbooks && env ANSIBLE_LOG_PATH=/root/apnscp-bootstrapper.log BOOTSTRAP_SH=/root/resume_apnscp_setup.sh  ansible-playbook -l localhost -c local bootstrap.yml' to resume
Installation failed

**Comment by natpix** [comment]
RUNNING HANDLER [common : Restart apnscp] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Unable to start service apnscp: Job for apnscp.service failed because the service did not take the steps required by its unit configuration.
    See "systemctl status apnscp.service" and "journalctl -xe" for details.
After  i ran
`cd /usr/local/apnscp/resources/playbooks && env ANSIBLE_LOG_PATH=/root/apnscp-bootstrapper.log BOOTSTRAP_SH=/root/resume_apnscp_setup.sh ansible-playbook -l localhost -c local bootstrap.yml`

i got this

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************

PLAY RECAP *****************************************************************************************************************************************************************************
localhost                  : ok=543  changed=4    unreachable=0    failed=1    skipped=272  rescued=0    ignored=0

**Comment by natpix** [comment]
Finally It worked after few restarts and reinstallation

**Comment by natpix** [comment]
Now, i am trying to change the username and password. 
It says -bash: cpcmd: command not found

**Comment by natpix** [comment]
how do i change username and password

**Comment by msaladna** [comment]
> Now, i am trying to change the username and password.
> It says -bash: cpcmd: command not found

Via [INSTALL.md](https://docs.apiscp.com/INSTALL/#provisioning)

> After install, load a new shell with the correct ApisCP environment.
> `exec $SHELL -i`



> how do i change username and password

Via [INSTALL.md](https://docs.apiscp.com/INSTALL/#after-install)
> Domains that have a properly qualified FQDN will receive notification once ApisCP is installed. If not, the admin username/password/contact can be reconfigured at anytime using ApisCP's API helper.
> `cpcmd auth:change-username 'NEWUSER'`
> `cpcmd auth:change-password 'NEWPASSWORD'`
> `cpcmd common:set-email 'NEW@EMAIL.COM'`
