### ISSUE TITLE
Setup Mail SPF, DMARC & DKIM

### ISSUE THREAD

**Issue by natpix** [apisnetworks/apnscp#43]
Hi, 

I have been going through the docs to learn how to setup 
SPF Records, DKIM and DMARC 

Can anyone guide on how to set this up ?

**Comment by msaladna** [comment]
I'm not sure I understand your question. See [Mail.md](https://docs.apiscp.com/admin/Mail/#delivery-requirements) for a rundown of all components and a detailed discussion of how these records are created.

**Comment by natpix** [comment]
I want to add SPF, DKIM and DMARC setting for using webmail services.

**Comment by msaladna** [comment]
See [Mail.md](https://docs.apiscp.com/admin/Mail/#delivery-requirements). Follow the instructions provided therein.

**Comment by natpix** [comment]
i have seen that doc, its not helpful.

**Comment by natpix** [comment]
Also, any setting if i change in dashboard, it thows an error alert. 
Does everything need to be set up from cmd line?

**Comment by msaladna** [comment]
> i have seen that doc, its not helpful.

Please elaborate on what concerns you're having and what you've done thus far. You may also be better serviced through our [community Discord](https://discord.gg/wDBTz6V) where you can connect with other users who have successfully deployed DKIM, DMARC, and SPF through ApisCP without incident. 

Lastly, if it throws an error, then the context of the message would be crucial to validating your concern.
