### ISSUE TITLE
Snapshot not working

### ISSUE THREAD

**Issue by natpix** [apisnetworks/apnscp#44]
Hi,

When i click on Snapshot, it says Action succeeded, but it doesn't do anything. it just refreshes page. It still shows Enable Snapshot.

**Comment by msaladna** [comment]
This was resolved in [v3.2.23](https://gitlab.com/apisnetworks/apnscp/-/tags/v3.2.23). Please don't open an issue here and on the community Discord unless asked to open it explicitly here.
