### ISSUE TITLE
Include spf records when selecting non-built-in email provider

### ISSUE THREAD

**Issue by shahaly** [apisnetworks/apnscp#45]
**Overview**

Email servers are starting to enforce SPF validation and rejecting emails where the spf record for the sender-domain doesn't contain a reference to the domain / ip from where the email originated. When using built-in email server, this isn't an issue since the standard spf entry created by apiscp contains both a and mx reference. However, when using a third party email provider, e.g. GMail, this can be a bit tricky because the a and mx pointers in the SPF don't fully encompass the servers Google might use to route the email. To mitigate this, Google requires that the SPF entry contain include:_spf.google.com in the SPF (https://support.google.com/a/answer/10685031).

**Current Behavior**
Used Gmail as my email method during domain creation and worked through the panel's spf record creator. This resulted in "v=spf1 a mx -all" as the proposed record because I'm a dummy and didn't realize I needed to also add the _spf.google.com in the inclusion list. 

Now, given that there are only a handful of third-party email vendors supported, would be nice if the SPF record wizard / dns setup upon creation added the right inclusion within the SPF record.

I noticed the issue in my spf setup when emails started bouncing. Ran a test through mxtools and received the following results:

![image](https://user-images.githubusercontent.com/69744963/142728389-2a637979-fd80-4dd3-9d2b-16d44a21e4a9.png)

Adding _spf.google.com in the inclusion list fixed it.

![image](https://user-images.githubusercontent.com/69744963/142728419-0aafc7f4-24f9-4729-ab5b-5786d1f41ccd.png)

**Proposed Behavior**
When selecting a third party email tool during the domain setup wizard, add the inclusion list SPF record by default. 

- Gmail: _spf.google.com
- MxRoute: mxroute.com

**Benefit of the Proposal**
Non-technical users that don't know much about mail routing and use a service like Gmail wouldn't need to manually update the SPF record when upon creation of the domain, it's already specified what email service they'd be using. For hosting providers, this may result in fewer of email delivery related cases.

**Comment by shahaly** [comment]
PS: DMARC isn't in scope here. That was solely me not having copied the key into CF just yet.

**Comment by msaladna** [comment]
How'd you go about setting this up? Setting mail,provider=gmail or keeping it default (builtin) and later changing the MX records without administratively changing these records *by changing mail,provider=gmail from mail,provider=builtin*?

As it's structured, that TXT record for both [GMail](https://gitlab.com/apisnetworks/apnscp/-/blob/master/lib/Opcenter/Mail/Providers/Gmail/Module.php#L42-47) and [MXRoute](https://gitlab.com/apisnetworks/apnscp/-/blob/master/lib/Opcenter/Mail/Providers/Mxroute/Api.php#L44-47) should be automatically resolved if you change mail providers but will not be resolved if you provision a site on a new server and the UUID conflicts.

**Comment by msaladna** [comment]
Updated initial remarks upon further inspection seeing they were ambiguous to the action

**Comment by shahaly** [comment]
Originally provisioned it using GMail with a fresh domain. Let me add another one over the next day or so on a fresh domain and fresh provision and I'll capture the spf record TXT file. Thanks @msaladna
