### ISSUE TITLE
can you create a mirror?

### ISSUE THREAD

**Issue by Neustradamus** [apisnetworks/apnscp#47]
Hello @apisnetworks team,

I first, I wish you a Happy New Year 2022!

Can you create a mirror between GitLab and GitHub?

Thanks in advance.

**Comment by msaladna** [comment]
GitHub has [different policies](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants) on code published to public repositories here that is incompatible or in a gray area with the ApisCP license.
