### ISSUE TITLE
Dns_Module#getRecordId has infinite recursion on simple (non-weighted) records

### ISSUE THREAD

**Issue by CherryDT** [apisnetworks/apnscp#48]
I am using the AWS Route 53 DNS provider and I encountered the problem that changes in the DNS manager would never complete and instead eventually get the frontend process killed with >200MB memory usage.

Investigation showed that this comes from an infinite recursion here:

https://gitlab.com/apisnetworks/apnscp/-/blob/master/lib/Module/Support/Dns.php#L117

If a record exists but is a simple record, i.e. not weighted and therefore without record ID, `getRecordId` will find the record but it won't have a record ID, and if `$id === null` then at the end `getRecordId` will call itself again with the same argument (`return $this->getRecordId($r);`), resulting in infinite recursion.

How to reproduce:

* Configure AWS provider
* Create a hosted zone in AWS Route 53
* Create a record in Route 53, for example a TXT record for `_test` with content `"ABC"` (use default routing policy "simple", not "weighted")
* Attempt to change the value of the record from `ABC` to `XYZ` in ApisCP and observe the bug happening

...and then:

* Update the record in Route 53, changing routing policy to "weighted", setting weight 100 and adding some random record ID there
* Attempt to change the value of the record in ApisCP again and observe the bug no longer happening

**Comment by msaladna** [comment]
Give this a go on edge now :+1:

```bash
cpcmd scope:set cp.update-policy edge-major
upcp
```
