### ISSUE TITLE
Cloudflare DNS proxy status not maintained on edit

### ISSUE THREAD

**Issue by scottaki** [apisnetworks/apnscp#49]
There seems to be a bug in the DNS implementation using Cloudflare as the DNS provider. If you have "proxy: true" set in the global default, creating new records will successfully enable the proxy status (orange cloud) in Cloudflare for this record. However, if you then edit an entry, which exists on both ApisCP and Cloudflare (as it should), the proxy status is disabled on Cloudflare with no warning in ApisCP.

The only way to re-enable it is to either (a) delete the record in ApisCP, add it again (pretend its a new record); or (b) log in to Cloudflare, and then re-enable proxy on each record individually.

This may be a limitation with the API, or something that has been addressed before, but I've discovered this just now when mass-updating DNS records to change the IP from an old server to current one... and then found I need to go into Cloudflare and modify each row again after making the IP change in ApisCP. Probably would have been faster to do all updates from Cloudflare in the first place...?

Is there any way to have ApisCP check the status, on update/edit, and maintain the current status at Cloudflare's end? Or, even better, allow management of the proxy status for each record within ApisCP?

Cheers all.

**Comment by msaladna** [comment]
Give this a go on edge now 👍

```
cpcmd scope:set cp.update-policy edge-major
upcp
```

**Comment by scottaki** [comment]
Brilliant @msaladna, that worked perfectly! Few issues with the upcp command, but a upcp --reset fixed that up.

Thanks for being so responsive. No doubt as to which panel I'm using moving forward. Cheers!
