### ISSUE TITLE
Feature Request: 2 Factor on launchpad with lockout on other services

### ISSUE THREAD

**Issue by TobyKLight** [apisnetworks/apnscp#5]
I understand it's impossible to put 2 factor login over every service individually. 
But certainly a good boost to my security would be a feature along the lines of:
- 2 factor on launchpad
- an optional lockout on other services (eg FTP, SSH) that's only unlocked by a successful 2 factor login.
- the lockout is selectable per service. 
- Time window for unlock is selectable eg default 2 hrs but can be set to 12 for letting an FTP job run over night.
- Multiuser would be great but I'd happily take it on admin only.
- If you did do multiuser could use that to solve problems where you need automated access to services. Eg Create a new user that doesn't use 2 factor but only has read only rights to needed files. This login could be used by a regular FTP backup service.  
- If you want to get really fancy could have a learning mode like fortification, where for a short period you go into 'full access' mode. Start your FTP connection. After that launchpad get shows you the IPs that accessed in full mode and you can select the ones to whitelist for the longer running 'limited mode'. 
- 2 factor reset would be via email so (as per now) admin email is still the keys to the castle. 2 factor was never a silver bullet but a boost non the less.

**Comment by msaladna** [comment]
Depends upon #11

**Comment by msaladna** [comment]
3.1 is next on the [list](https://www.reddit.com/r/apnscp/comments/azjupa/v3023_released_transitioning_to_v31_development/). Open a ticket within you panel so I can track this. A link back to this works or "dfkm24qwd", something to internally track.

**Comment by TobyKLight** [comment]
Done, thanks again for keeping this one on the radar

**Comment by msaladna** [comment]
Moved to [feedback.apiscp.com#30](https://feedback.apiscp.com/posts/30/2fa-with-lockout-on-other-services)
