### ISSUE TITLE
Cannot create multiple TXT DNS records

### ISSUE THREAD

**Issue by CherryDT** [apisnetworks/apnscp#52]
I'm getting an error like this trying to add a second TXT record to the same (sub)domain:

>  Action failed
> 
> Failed to create record `example.com' type TXT: [Tried to create resource record set [name='example.com.', type='TXT'] but it already exists]

How can I do that? Multiple TXT records should be perfectly valid. I checked if it supports multiple lines maybe, but that's not supported either. I know on Route 53 you can't do that but instead there you can simply put multiple lines into the textarea field and it works the same, but ApisCP doesn't let me do that either.

I need to add both an SPF record and an unrelated validation record for a service.

I now handled it directly in Route 53, and now it _does_ show up as two records in ApisCP. But the issue is that it cannot be created from ApisCP directly.

**Comment by msaladna** [comment]
Thanks for the bug report. This is implemented in apisnetworks/apiscp-dns-aws@664bf36. To verify the code, hop on [edge-major](https://docs.apiscp.com/UPGRADING/#panel-updates), which will keep your panel on edge until the next release.

```bash
cpcmd scope:set cp.update-policy edge-major
upcp
```

**Comment by msaladna** [comment]
This rejection is coming directly from Route53. I'm able to reproduce the behavior through their console.
